### ISSUE TITLE
HttpRequestClientHostIPEnricher throws exception with ASP.NET Integrated Mode

### ISSUE THREAD

**Issue by brettveenstra** [serilog-web/classic#1]
Logging events from `Application_Start` in global.asax can throw Exception if enriching with `HttpRequestClientHostIPEnricher`

for background/discussion see http://stackoverflow.com/questions/2518057/request-is-not-available-in-this-context

**Comment by nblumhardt** [comment]
This is fixed by #9.

**Comment by douglasg14b** [comment]
@nblumhardt 

Seemingly not fixed, I'm using the current version and experiencing this.

>2020-02-25T18:24:25.8538668Z Exception System.Web.HttpException (0x80004005): Request is not available in this context
   at System.Web.HttpContext.get_Request()
   at SerilogWeb.Classic.Enrichers.HttpRequestUserAgentEnricher.Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
   at Serilog.Core.Enrichers.SafeAggregateEnricher.Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory) in C:\projects\serilog\src\Serilog\Core\Enrichers\SafeAggregateEnricher.cs:line 39 caught while enriching Serilog.Events.LogEvent with SerilogWeb.Classic.Enrichers.HttpRequestUserAgentEnricher.

**Comment by nblumhardt** [comment]
It looks like some usage of `HttpContext.Current.Request` in:

https://github.com/serilog-web/classic/blob/master/src/SerilogWeb.Classic/Classic/Enrichers/HttpRequestUserAgentEnricher.cs#L43

should be replaced with `HttpContextCurrent.Request`. Guessing this is a regression.

**Comment by tsimbalar** [comment]
Ah yes good catch 👍  

I didn't know about this `HttpContext.Current.Request` getter throwing in some cases ... that seems like an unpleasant violation of the principle of least astonishment, but 🤷‍♂  ... 

A [quick search](https://github.com/serilog-web/classic/search?p=1&q=HttpContext.Current&unscoped_q=HttpContext.Current) for `HttpContext.Current` in this repo reveals that we are using it in many places. 

I understand that the only problematic one is `HttpContext.Current.Request` , and that `HttpContext.Current.Items` , `HttpContext.Current.Session`, `HttpContext.Current.User` are safe to use ? (i.e. they might be null, but accessing the property won't throw an exception) ... I haven't done any ASP.NET in quite a while.

**Comment by tsimbalar** [comment]
@douglasg14b [SerilogWeb.Classic 5.0.56 ](https://www.nuget.org/packages/SerilogWeb.Classic/5.0.56) has just been released , it should fix the issue.

**Comment by douglasg14b** [comment]
Thanks! I'll give it a try when I'm next able to get a bug fix iteration approved.
